book := stapledon-last-and-first-men

srcdir := src

opf := content.opf

content := toc.xhtml \
           text/cover.xhtml \
           text/title-page.xhtml \
           text/foreword.xhtml \
           text/introduction.xhtml \
           text/preface.xhtml \
           text/chapter-01.xhtml \
           text/chapter-02.xhtml \
           text/chapter-03.xhtml \
           text/chapter-04.xhtml \
           text/chapter-05.xhtml \
           text/chapter-06.xhtml \
           text/chapter-07.xhtml \
           text/chapter-08.xhtml \
           text/chapter-09.xhtml \
           text/chapter-10.xhtml \
           text/chapter-11.xhtml \
           text/chapter-12.xhtml \
           text/chapter-13.xhtml \
           text/chapter-14.xhtml \
           text/chapter-15.xhtml \
           text/chapter-16.xhtml \
           text/subchapter-01-1.xhtml \
           text/subchapter-01-2.xhtml \
           text/subchapter-01-3.xhtml \
           text/subchapter-01-4.xhtml \
           text/subchapter-02-1.xhtml \
           text/subchapter-02-2.xhtml \
           text/subchapter-02-3.xhtml \
           text/subchapter-03-1.xhtml \
           text/subchapter-03-2.xhtml \
           text/subchapter-03-3.xhtml \
           text/subchapter-04-1.xhtml \
           text/subchapter-04-2.xhtml \
           text/subchapter-04-3.xhtml \
           text/subchapter-04-4.xhtml \
           text/subchapter-04-5.xhtml \
           text/subchapter-05-1.xhtml \
           text/subchapter-05-2.xhtml \
           text/subchapter-05-3.xhtml \
           text/subchapter-05-4.xhtml \
           text/subchapter-06-1.xhtml \
           text/subchapter-06-2.xhtml \
           text/subchapter-07-1.xhtml \
           text/subchapter-07-2.xhtml \
           text/subchapter-07-3.xhtml \
           text/subchapter-08-1.xhtml \
           text/subchapter-08-2.xhtml \
           text/subchapter-08-3.xhtml \
           text/subchapter-08-4.xhtml \
           text/subchapter-09-1.xhtml \
           text/subchapter-09-2.xhtml \
           text/subchapter-09-3.xhtml \
           text/subchapter-10-1.xhtml \
           text/subchapter-10-2.xhtml \
           text/subchapter-10-3.xhtml \
           text/subchapter-10-4.xhtml \
           text/subchapter-11-1.xhtml \
           text/subchapter-11-2.xhtml \
           text/subchapter-11-3.xhtml \
           text/subchapter-11-4.xhtml \
           text/subchapter-12-1.xhtml \
           text/subchapter-12-2.xhtml \
           text/subchapter-12-3.xhtml \
           text/subchapter-12-4.xhtml \
           text/subchapter-13-1.xhtml \
           text/subchapter-13-2.xhtml \
           text/subchapter-13-3.xhtml \
           text/subchapter-14-1.xhtml \
           text/subchapter-14-2.xhtml \
           text/subchapter-14-3.xhtml \
           text/subchapter-15-1.xhtml \
           text/subchapter-15-2.xhtml \
           text/subchapter-15-3.xhtml \
           text/subchapter-15-4.xhtml \
           text/subchapter-16-1.xhtml \
           text/subchapter-16-2.xhtml \
           text/subchapter-16-3.xhtml \
           text/colophon.xhtml \
           style/style.css \
           style/toc.css \
           img/cover.svg \
           img/cover.png \
           img/time-scale-1.svg \
           img/time-scale-2.svg \
           img/time-scale-3.svg \
           img/time-scale-4-5.svg \
           img/time-scale-4.svg \
           img/time-scale-5.svg \
           img/cc-zero.svg \
           img/publicdomain.svg \
           toc.ncx
